// AI Content Generation API - EXPERIMENTAL
// Generates blog drafts, descriptions, translations, alt text, and images

import { NextRequest, NextResponse } from 'next/server';
import { revalidatePath } from 'next/cache';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// AI Provider types
type AIProvider = 'openai' | 'anthropic' | 'ollama' | 'mock';

interface AIConfig {
  provider: AIProvider;
  apiKey?: string;
  apiUrl?: string;
  model?: string;
}

interface GenerationRequest {
  type: 'blog-draft' | 'project-description' | 'translate' | 'alt-text' | 'image';
  input: string;
  options?: {
    language?: 'en' | 'fr';
    tone?: 'professional' | 'casual' | 'technical' | 'creative';
    maxLength?: number;
    keywords?: string[];
    title?: string;
    context?: string;
  };
}

interface GenerationResponse {
  success: boolean;
  content?: string;
  imageUrl?: string;
  error?: string;
  provider: AIProvider;
  requiresReview: true;
}

// Get AI configuration from environment
function getAIConfig(): AIConfig {
  if (process.env.OPENAI_API_KEY) {
    return {
      provider: 'openai',
      apiKey: process.env.OPENAI_API_KEY,
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
    };
  }

  if (process.env.ANTHROPIC_API_KEY) {
    return {
      provider: 'anthropic',
      apiKey: process.env.ANTHROPIC_API_KEY,
      model: process.env.ANTHROPIC_MODEL || 'claude-3-haiku-20240307',
    };
  }

  if (process.env.OLLAMA_API_URL) {
    return {
      provider: 'ollama',
      apiUrl: process.env.OLLAMA_API_URL,
      model: process.env.OLLAMA_MODEL || 'llama2',
    };
  }

  // Fallback to mock for development
  return { provider: 'mock' };
}

// OpenAI generation
async function generateWithOpenAI(
  prompt: string,
  config: AIConfig,
  systemPrompt?: string
): Promise<string> {
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${config.apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: config.model || 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt || 'You are a helpful assistant.' },
        { role: 'user', content: prompt },
      ],
      max_tokens: 2000,
      temperature: 0.7,
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI error: ${response.statusText}`);
  }

  const data = await response.json();
  return data.choices[0]?.message?.content || '';
}

// Anthropic generation
async function generateWithAnthropic(
  prompt: string,
  config: AIConfig,
  systemPrompt?: string
): Promise<string> {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': config.apiKey!,
      'Content-Type': 'application/json',
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: config.model || 'claude-3-haiku-20240307',
      max_tokens: 2000,
      system: systemPrompt || 'You are a helpful assistant.',
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  if (!response.ok) {
    throw new Error(`Anthropic error: ${response.statusText}`);
  }

  const data = await response.json();
  return data.content[0]?.text || '';
}

// Ollama generation (local)
async function generateWithOllama(
  prompt: string,
  config: AIConfig
): Promise<string> {
  const response = await fetch(`${config.apiUrl}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: config.model || 'llama2',
      prompt,
      stream: false,
    }),
  });

  if (!response.ok) {
    throw new Error(`Ollama error: ${response.statusText}`);
  }

  const data = await response.json();
  return data.response || '';
}

// Mock generation for development
async function generateMock(type: string, input: string): Promise<string> {
  await new Promise((resolve) => setTimeout(resolve, 500));

  switch (type) {
    case 'blog-draft':
      return `# ${input}

## Introduction
This is an AI-generated draft about "${input}". As a developer and creative technologist, I've been exploring this topic extensively...

## Key Points

### First Insight
One of the most interesting aspects is how this technology continues to evolve. The implications for future development are significant.

### Technical Details
From a technical standpoint, we need to consider several factors:
- Performance optimization
- User experience considerations
- Scalability challenges

## Conclusion
This draft requires human review and editing before publication. Please fact-check and add your personal insights.

---
*Generated by AI - Review required before publishing*`;

    case 'project-description':
      return `An innovative web application featuring ${input}. Built with cutting-edge technologies including React 19, Next.js 16, and Three.js for 3D graphics.

This project demonstrates advanced frontend engineering with focus on:
- Performance optimization
- Accessible user interfaces
- Modern web standards

*AI-generated description - Please review and edit*`;

    case 'translate':
      return `[Translated content for: "${input}"]

This is a machine translation. Please review for accuracy and cultural appropriateness.`;

    case 'alt-text':
      return `A visual representation showing ${input}. The image contains various elements relevant to the context.`;

    default:
      return `AI-generated content for: ${input}. Please review before publishing.`;
  }
}

// Generate blog article draft
async function generateBlogDraft(
  title: string,
  options: GenerationRequest['options'] = {}
): Promise<string> {
  const tone = options?.tone || 'professional';
  const language = options?.language || 'en';
  const maxLength = options?.maxLength || 1000;

  const systemPrompt = `You are a professional content writer for a tech blog. Generate well-structured blog posts with proper headings, bullet points, and engaging content. ${language === 'fr' ? 'Write in French.' : 'Write in English.'}`;

  const prompt = `Write a blog post draft with the title "${title}".
Tone: ${tone}
Target length: ~${maxLength} words
${options?.keywords ? `Keywords to include: ${options.keywords.join(', ')}` : ''}
${options?.context ? `Additional context: ${options.context}` : ''}

Include:
- An engaging introduction
- 3-5 main sections with headings
- Code examples if technical
- A conclusion

IMPORTANT: Add a note at the end that this is AI-generated and requires human review.`;

  return generateContent(prompt, systemPrompt);
}

// Generate project description
async function generateProjectDescription(
  projectName: string,
  options: GenerationRequest['options'] = {}
): Promise<string> {
  const systemPrompt = 'You write compelling project descriptions for portfolio sites. Focus on technical achievements and user value.';

  const prompt = `Write a project description for "${projectName}".
${options?.context ? `Context: ${options.context}` : ''}
${options?.tone ? `Tone: ${options.tone}` : ''}

Include:
- One-line summary
- Technical stack used
- Key features (3-5 bullet points)
- Challenges overcome

Keep it under 200 words. Add note that this is AI-generated.`;

  return generateContent(prompt, systemPrompt);
}

// Translate content
async function translateContent(
  content: string,
  targetLanguage: 'en' | 'fr'
): Promise<string> {
  const systemPrompt = `You are a professional translator. Translate content while preserving meaning, tone, and formatting. ${targetLanguage === 'fr' ? 'Translate to French.' : 'Translate to English.'}`;

  const prompt = `Translate the following content. Preserve markdown formatting, code blocks, and structure.

Content to translate:
${content}

IMPORTANT: Add a note at the end that this is a machine translation and requires human review.`;

  return generateContent(prompt, systemPrompt);
}

// Generate alt text for images
async function generateAltText(imageDescription: string): Promise<string> {
  const systemPrompt = 'Generate concise, descriptive alt text for images following accessibility best practices. Maximum 125 characters.';

  const prompt = `Generate alt text for an image described as: "${imageDescription}"

The alt text should be:
- Descriptive but concise
- Under 125 characters
- Focused on important visual information
- Useful for screen reader users`;

  return generateContent(prompt, systemPrompt);
}

// Generate image using DALL-E or similar
async function generateImage(prompt: string): Promise<string> {
  const config = getAIConfig();

  if (config.provider === 'openai' && config.apiKey) {
    const response = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt: `${prompt}. Minimalist, professional style suitable for a tech blog.`,
        n: 1,
        size: '1024x1024',
        response_format: 'url',
      }),
    });

    if (!response.ok) {
      throw new Error(`Image generation error: ${response.statusText}`);
    }

    const data = await response.json();
    return data.data[0]?.url || '';
  }

  if (config.provider === 'ollama' && config.apiUrl) {
    // Use Stable Diffusion via Ollama if available
    try {
      const response = await fetch(`${config.apiUrl}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'stablediffusion',
          prompt,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        return data.image || '';
      }
    } catch {
      // Fall through to mock
    }
  }

  // Mock image URL
  return `data:image/svg+xml,${encodeURIComponent(`
    <svg width="1024" height="1024" xmlns="http://www.w3.org/2000/svg">
      <rect width="1024" height="1024" fill="#1a1a2e"/>
      <text x="512" y="512" font-family="Arial" font-size="48" fill="#ffffff" text-anchor="middle">
        AI Image Placeholder
      </text>
      <text x="512" y="580" font-family="Arial" font-size="24" fill="#888888" text-anchor="middle">
        ${prompt.substring(0, 50)}...
      </text>
    </svg>
  `)}`;
}

// Main content generation function
async function generateContent(prompt: string, systemPrompt?: string): Promise<string> {
  const config = getAIConfig();

  switch (config.provider) {
    case 'openai':
      return generateWithOpenAI(prompt, config, systemPrompt);
    case 'anthropic':
      return generateWithAnthropic(prompt, config, systemPrompt);
    case 'ollama':
      return generateWithOllama(`${systemPrompt || ''}\n\n${prompt}`, config);
    case 'mock':
      return generateMock('default', prompt);
    default:
      throw new Error('No AI provider configured');
  }
}

// POST handler for generation requests
export async function POST(request: NextRequest) {
  try {
    const body: GenerationRequest = await request.json();
    const { type, input, options } = body;

    if (!type || !input) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields: type and input' },
        { status: 400 }
      );
    }

    let content: string | undefined;
    let imageUrl: string | undefined;
    const config = getAIConfig();

    switch (type) {
      case 'blog-draft':
        content = await generateBlogDraft(input, options);
        break;

      case 'project-description':
        content = await generateProjectDescription(input, options);
        break;

      case 'translate':
        content = await translateContent(input, options?.language || 'en');
        break;

      case 'alt-text':
        content = await generateAltText(input);
        break;

      case 'image':
        imageUrl = await generateImage(input);
        break;

      default:
        return NextResponse.json(
          { success: false, error: `Unknown generation type: ${type}` },
          { status: 400 }
        );
    }

    const response: GenerationResponse = {
      success: true,
      content,
      imageUrl,
      provider: config.provider,
      requiresReview: true,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('[AI Generate] Error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        provider: getAIConfig().provider,
        requiresReview: true,
      } as GenerationResponse,
      { status: 500 }
    );
  }
}

// GET handler for provider info
export async function GET() {
  const config = getAIConfig();

  return NextResponse.json({
    provider: config.provider,
    model: config.model,
    available: config.provider !== 'mock',
    requiresReview: true,
    capabilities: {
      'blog-draft': true,
      'project-description': true,
      'translate': true,
      'alt-text': true,
      'image': config.provider === 'openai' || config.provider === 'mock',
    },
  });
}
